// <auto-generated />
namespace GeneralStore.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class space_for_Full_Name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(space_for_Full_Name));
        
        string IMigrationMetadata.Id
        {
            get { return "202012101958546_space_for_Full_Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
